---

- name: Rotate tower password from hashicorp vault
  hosts: localhost
  connection: local
  vars:
    org: demo
    secret: "{{ lookup('hashi_vault', 'secret={{ hashi_secret }} token={{ hashi_token }} url={{ hashi_url }}') }}"
  tasks:

  - name: Update tower credential
    tower_credential:
      tower_verify_ssl: no
      username: "{{ tower_user }}"
      password: "{{ tower_password }}"
      tower_host: "{{ tower_host }}"
      name: root
      description: root password
      organization: "{{ tower_org }}"
      username: root
      password: "{{ secret.password }}"
      state: present
      kind: ssh
