---

- name: Rotate tower password from hashicorp vault
  hosts: localhost
  connection: local
  vars:
    org: demo
    secret: "{{ lookup('hashi_vault', 'secret={{ hashi_secret }} token={{ hashi_token }} url={{ hashi_url }}') }}"
  tasks:

  - debug:
      msg: "password is {{ secret.password }}"
      verbosity: 2

  - name: Update tower credential
    tower_credential:
      tower_verify_ssl: no
      name: root
      description: root password
      organization: "{{ tower_org }}"
      username: root
      password: "{{ secret.password }}"
      state: present
      kind: ssh
